spring:
  #influxDB配置信息
  influx:
    url: http://localhost:8086
    user: root
    password: root
  #MQTT配置信息
  mqtt:
    username: admin
    password: public
    url: tcp://127.0.0.1:1883
    default:
      topic: topic
    client:
      id: iot-demo-spring
    consumer:
      clientId: iot-demo-spring-consumer
      defaultTopic: topic

  datasource:
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""
    url: jdbc:sqlite:test.sqlite
server:
  port: 8083
